title: "Katie Bucks the Invisible Fucks!"
description: "Some short site description"
url: "https://katiebucks.github.io"
baseurl: "/katiebucks.xyz"
timezone: "UTC"

sass:
  sass_dir: "_sass"
  style: compressed

# Permalinks
permalink: "/:title/"   # or set to "pretty"

# Build settings
markdown: kramdown
theme: minima

# Pagination
paginate: 10
paginate_path: "/page:num/"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - .git
  - .github

plugins:
  - jekyll-feed
  - jekyll-paginate

collections:
  pages:
    output: true
    permalink: /:name/
  posts:
    output: true
    permalink: /:year/:month/:day/:title/
  categories:
    output: true

# Navbar Links
nav_links:
  - title: Home
    url: "/"
  - title: About
    url: "/about/"
  - title: Privacy Guide
    url: "/privacy-guide/"
  - title: PGP
    url: "/pgp/"

assets:
  css: "/assets/css/main.css"
  images: "/assets/images/"
  js: "/assets/js/"

# Default Layouts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Optional relative links config
relative_links:
  enabled: false    #true?
  collections: true

# Remember: Jekyll won't auto-generate CSP from this block
csp:
  default-src: "'self'"
  img-src: "'self' data:"
  style-src: "'self' 'unsafe-inline'"
  font-src: "'self'"
  script-src: "'self'"