title: "Katie Bucks the Invisible FUCKS!"
description: "Sum bullsheet!"
baseurl: ""
url: "https://katiebucks.xyz"
timezone: "UTC"

permalink: "/:title/"
markdown: kramdown
paginate: 20
paginate_path: "/page:num/"
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - .git
  - .github

plugins:
  - jekyll-feed
  - jekyll-paginate

collections:
  pages:
    output: true
    permalink: /:name/
  posts:
    output: true
    permalink: /:year/:month/:day/:title/
  categories:
    output: true